version: "3.3"

services:

  app: &app
    tty: true
    build:
      context: .
      args:
        requirements: requirements.txt
    environment:
      - DEBUG=True
      - SETTINGS_FILE=api.dev.yml
      - PYTHONUNBUFFERED=1
    env_file:
      ./prod.env
    restart: always
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis
    ports:
      - 8081:8000
    networks:
      stonetwork:
        aliases:
          - local.app.stonehenge

  postgres:
    image: postgres:11
    container_name: stonehenge_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432
    networks:
      stonetwork:
        aliases:
          - local.db.stonehenge

  app_for_test:
    <<: *app
    container_name: stonehenge_test
    ports:
      - 8082:8082
    entrypoint: py.test -v -p no:warnings
    command: ''

  nginx:
    image: nginx:mainline-alpine
    container_name: "stonehenge_nginx"
    depends_on:
      - app
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./stonehenge/static:/usr/share/nginx/static
    networks:
      stonetwork:
        aliases:
          - local.server.stonehenge

  redis:
    image: "redis:alpine"
    command: redis-server --requirepass redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      stonetwork:
        aliases:
          - local.redis.stonehenge

networks:
  stonetwork:
