version: "3.3"

services:

  app: &app
    tty: true
    container_name: app
    build:
      context: .
      args:
        requirements: requirements.txt
    environment:
      - DEBUG=True
      - SETTINGS_FILE=api.dev.yml
      - PYTHONUNBUFFERED=1
    env_file:
      ./prod.env
    restart: always
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis
    ports:
      - 8081:8000
    networks:
      stonetwork:
        aliases:
          - app

  postgres:
    image: postgres:11
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432
    networks:
      stonetwork:
        aliases:
          - local.db.stonehenge

  app_for_test:
    <<: *app
    container_name: test
    entrypoint: /bin/bash
    ports: [8090]
    working_dir: /app
    command: ''

  nginx:
    build:
      context: nginx
    container_name: nginx
    depends_on:
      - app
    ports:
      - "8080:8080"
      - "1935:1935"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/default.conf:/etc/nginx/nginx.conf
      - ./stonehenge/static:/usr/share/nginx/static
    networks:
      stonetwork:
        aliases:
          - local.server.stonehenge

  redis:
    image: "redis:alpine"
    container_name: redis
    command: redis-server --requirepass redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      stonetwork:
        aliases:
          - local.redis.stonehenge

networks:
  stonetwork:
