name: Python application from docker-compose

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Create stub for prod.env
        run: touch prod.env
      - name: Build container
        run: docker-compose up --build -d app_for_test
      - name: Run tests
        run: docker-compose exec -T app_for_test pytest --html=report.html
      - name: Upload result
        uses: actions/upload-artifact@v1
        with:
          name: homework
          path: report.html
