name: Python application from docker-compose

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Stub for prod.env
        run: touch prod.env
      - name: Integration test
        run: docker-compose up -d app_for_test
      - name: Run tests
        run: docker-compose exec -T app_for_test pytest --html=report.html
      - name: Upload math result for job 1
        uses: actions/upload-artifact@v1
        with:
          name: homework
          path: report.html
